trigger:
  batch: true
  branches:
    include:
      - "*"

pr: none

variables:
  buildConfiguration: 'release'
  buildPlatform: 'anycpu'

pool:
  vmImage: 'ubuntu-latest'

stages:
  - stage: build
    jobs:
      - job: build
        steps:
        - task: DotNetCoreCLI@2
          displayName: Restore
          inputs:
            command: restore
            projects: 'src/**/*.csproj'
            noCache: true

        - task: DotNetCoreCLI@2
          displayName: Build
          inputs:
            projects: 'src/**/*.csproj'
            arguments: '--configuration $(buildConfiguration) --no-restore'

        - task: DotNetCoreCLI@2
          displayName: 'Publish Function App'
          inputs:
            command: publish
            publishWebProjects: false
            projects: 'src/Chelnak.Blob2S3.Functions/Chelnak.Blob2S3.Functions.csproj'
            arguments: '--configuration $(buildConfiguration) --output $(build.artifactstagingdirectory)/publish --no-restore --no-build'

        - task: CopyFiles@2
          displayName: 'Copy Files to: $(build.artifactstagingdirectory)'
          inputs:
            Contents: |
              azure/**
            TargetFolder: '$(build.artifactstagingdirectory)/publish'
            OverWrite: true

        - publish: '$(build.artifactstagingdirectory)/publish'
          artifact: Publish

  - stage: deploy
    condition: and(succeeded(), eq(variables['build.sourceBranch'], 'refs/heads/master'))
    dependsOn: build
    jobs:
      - deployment:
        environment: TEST
        variables:
          envLower: ${{ lower(Environment.Name) }}
        strategy:
          runOnce:
            deploy:
              steps:
                - download: current
                  artifact: Publish
                - task: AzureResourceManagerTemplateDeployment@3
                  inputs:
                    deploymentScope: 'Subscription'
                    azureResourceManagerConnection: 'Visual Studio Enterprise(7db81549-e1e7-467b-9c24-04b81630eeaa)'
                    subscriptionId: '7db81549-e1e7-467b-9c24-04b81630eeaa'
                    location: 'UK South'
                    templateLocation: 'Linked artifact'
                    csmFile: '$(Pipeline.Workspace)/Publish/azure/template.json'
                    overrideParameters: '-serviceName "$(ServiceName) -resourceEnvironmentName "$(envLower)" -AwsAccessKey "$(AwsAccessKey)" -AwsSecretKey "$(AwsSecretKey)" -AwsBucketName "$(AwsBucketName)"'
                    deploymentMode: 'Incremental'
